<?php

/**
 * Implements hook_form_alter()
 */
function pnw_custom_form_alter(&$form, &$form_state, $form_id) {
 //  dpm($form_id, 'form_id');
  

  switch ($form_id) {
    // dpm($form, 'form');
    case 'views_form_related_images_reorder_images':

      $form['actions']['submit']['#submit'][] = 'reorder_images_submit';
      
    break;

    case 'search_block_form':
      //dpm($_GET, 'get values');
      $form['search_block_form']['#size'] = 16;
      $form['actions']['submit']['#value'] = 'go!';
      // set default text for search input
      if (isset($_GET['q']) && (strpos($_GET['q'], 'search/content/') !== FALSE) ) {
        $search_text = str_replace('search/content/', '', $_GET['q']);
      }
      else {
        $search_text = 'Enter search terms';
      }
      
      $form['search_block_form']['#default_value'] = $search_text;
     
      $form['search_block_form']['#attributes'] = array(
        'onfocus' => "if (this.value == '$search_text') {this.value = '';}",
        'onblur' => "if (this.value == '') {this.value = '$search_text';}");

    break;


    case 'search_form':
      //dpm($form, 'form');
      unset($form['basic']['keys']['#title']);
      $form['basic']['keys']['#size'] = 18;
      $form['basic']['submit']['#value'] = 'go!';

    break;

    case 'image_node_form':
      /**
      * Implements hook_wysiwyg_editor_settings_alter()
      */
      function pnw_custom_wysiwyg_editor_settings_alter(&$settings, $context) {
        if ($context['profile']->editor == 'ckeditor') {
          $settings['height'] = 100;
        }
      }

      // add default text to image field
      $form['field_image']['und'][0]['#default_value']['alt'] = t('Photo of insect');
    break;

    case 'homepagephoto_node_form':
      // add default text to image field
      $form['field_photo']['und'][0]['#default_value']['alt'] = t('Homepage photo');

    break;

    case 'announcement_node_form':
      /**
      * Implements hook_wysiwyg_editor_settings_alter()
      */
      function pnw_custom_wysiwyg_editor_settings_alter(&$settings, $context) {
        if ($context['profile']->editor == 'ckeditor') {
          $settings['height'] = 400;
        }
      }

    break; 

  }

}

/**
 * Redirects user to node view after reordering images
 */
function reorder_images_submit($form, &$form_state) {
  drupal_set_message('Images reordered');
  $form_state['redirect'] = 'node/' . $form_state['build_info']['args'][0]->args[0];
}

 